export { App } from './App/App'
export { Content } from './Content/Content'
export { Footer } from './Footer/Footer'
export { Header } from './Header/Header'
export { MarioColorText } from './MarioColorText/MarioColorText'
export { ThemeToggle } from './ThemeToggle/ThemeToggle'
